server:
  port: 8081
spring:
  application:
    name: event-service
  datasource:
    url: jdbc:postgresql://localhost:5432/event_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
